<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class TosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Page::firstOrCreate(
            [
                'title->en' => 'Terms of Service',
            ],
            [
                'title->fr' => 'Conditions d’utilisation',
                'content->en' => '
Please read these terms of service carefully.

Institute for Research and Development on Inclusion and Society (“**IRIS**”, “**we**”, “**us**” or “**our**”) invites you (“**you**” or “**your**”) to join The Accessibility Exchange, a platform enabling diverse people with disabilities, Deaf persons and their supporters, and community organizations, to connect with one another, with federally regulated organizations (“**FROs**”) and with other organizations (together with FROs, the “**Project Proponents**”) for the purpose of developing accessibility plans or other related services. You can access The Accessibility Exchange at (<:home>) or on our mobile applications (the “**Platform**”). These terms of service and the IRIS Privacy Policy (together, the “**Terms**”) govern your use of the Platform and represent a legally binding agreement between you and IRIS.

By clicking to accept the Terms or otherwise using the Platform you agree to be bound by these Terms.

{.toc .ignore-counter}
## Table of Contents

1. [DEFINITIONS](#definitions)
2. [IRIS IS NOT A PARTY TO ANY PROJECT OR PROJECT AGREEMENT UNLESS EXPLICITLY STATED OTHERWISE](#iris-is-not-a-party-to-any-project-or-project-agreement-unless-explicitly-stated-otherwise)
3. [ACCESS AND USE OF THE PLATFORM](#access-and-use-of-the-platform)
4. [PRIVACY AND CONFIDENTIALITY](#privacy-and-confidentiality)
5. [SECURITY](#security)
6. [CONDITIONS OF USE](#conditions-of-use)
7. [USER CONTENT](#user-content)
8. [THIRD PARTY CONTENT AND SERVICES](#third-party-content-and-services)
9. [INTELLECTUAL PROPERTY RIGHTS](#intellectual-property-rights)
10. [LICENSES](#licenses)
11. [USER REPRESENTATIONS](#user-representations)
12. [INDEMNITY AND RELEASE](#indemnity-and-release)
13. [DISCLAIMER OF WARRANTIES](#disclaimer-of-warranties)
14. [LIMITATION OF LIABILITY](#limitation-of-liability)
15. [USER DISPUTES](#user-disputes)
16. [TERMINATION](#termination)
17. [SURVEYS](#surveys)
18. [GENERAL](#general)
19. [QUESTIONS](#questions)

## DEFINITIONS

1. “**Accessibility Consultant**” means an individual or organization helping Project Proponents design, facilitate and complete their Projects.
2. “**Community Connector**” means an individual or organization helping connect communities to Project Proponents seeking knowledge about how to connect with and/or support the community or Consultation Participants.
3. “**Consultation Participant**” means an individual or organization participating in consultations hosted by Project Proponents.
4. “**Consultants**” means an Accessibility Consultant, Community Connector, or Consultation Participants, as the context may require.
5. “**Content**” means documents, including agreements or memorandums of understanding, code, links, video, images, information, data, text, software, music, sound, photographs, images, graphics, messages, financial information, postings, files, identification, video, key word data and other advertising content, and other information or materials.
6. “**Demographic Information**” has the meaning set out in section 3(a) of these Terms.
7. “**FRO**” has the meaning set out in the opening paragraph of these Terms.
8. “**Indemnitees**” has the meaning set out in Section 12(a) of these Terms.
9. “**IRIS Privacy Policy**” has the meaning set out in Section 4 of these Terms.
10. “**IRIS Trademarks**” has the meaning set out in Section 9(b) of these Terms.
11. “**Personal Contact Information**” has the meaning set out in 3(a) of these Terms.
12. “**Project**” means any engagement to develop an accessibility plan or to undertake other activities to improve accessibility, between a Consultant and a Project Proponent pursuant to a Project Agreement.
13. “**Project Agreement**” has the meaning set out in Section 2(b) of these Terms.
14. “**Project Proponents**” has the meaning set out in the opening paragraph of these Terms.
15. “**Registration Information**” has the meaning set out in Section 3(a) of these Terms.
16. “**Service Content**” has the meaning set out in Section 9(a) of these Terms.
17. “**Services**” means the services that IRIS provides in connection with the Platform. For greater certainty, such Services specifically exclude any Third Party Services, or any services provided by Accessibility Consultants, Community Connectors, or Consultation Participants.
18. “**Submissions**” has the meaning set out in Section 10(c) of these Terms.
19. “**Third Party Content**” has the meaning set out in Section 8(a) of these Terms.
20. “**Third Party Provider**” has the meaning set out in Section 8(a) of these Terms.
21. “**Third Party Service**” has the meaning set out in Section 8(b) of these Terms.
22. “**Third Party Terms**” has the meaning set out in Section 8(b) of these Terms.
23. “**Underaged Person**” has the meaning set out in Section 3(a) of these Terms.
24. “**Upload**” means to upload, post or publish on the Platform.
25. “**User**” or “**you**” means a Project Proponent or Consultant, as the circumstances may indicate or require.
26. “**User Content**” has the meaning set out in Section 7(a) of these Terms.

## IRIS IS NOT A PARTY TO ANY PROJECT OR PROJECT AGREEMENT UNLESS EXPLICITLY STATED OTHERWISE

1. **The Platform is a Venue.** The Platform serves as a venue that:
    1. provides digital tools for Project Proponents to propose Projects and enter into relationships with Consultants who can assist them with the design and development of such Projects; and
    2. provides digital tools for Consultants to advertise their services, enter into relationships with Project Proponents, assist in the design and development of Projects.

    **USE OF THE PLATFORM, ANY SERVICE CONTENT AND THE SERVICES IS AT USER’S DISCRETION AND RISK.**

2. **Projects and Project Agreements.** IRIS is not a party to any agreements, transactions, projects or arrangements (“**Project Agreements**”) entered into between Project Proponents and Consultants unless explicitly agreed to. While IRIS provides the Platform and Services enabling you to engage in Projects and facilitate the payment for certain services, IRIS is not involved in any way in the Project other than through the provision of the Services, nor is IRIS party to the Project Agreements, except for any transactions for services expressly entered into between IRIS and Users. You understand and agree that IRIS will not be liable under any circumstances for the content or enforcement of any Project Agreement between you and another User, as applicable. You further understand and agree that while IRIS requires Users to submit true, accurate, current and complete information, IRIS cannot guarantee the qualifications of any Consultant or the success of any Project.
3. **Disclaimer.** All notices, Project Agreements and related documents made available on or through the Platform, either by IRIS, other Users, or generated as a Third Party Service on or through the Platform, are not legally reviewed, endorsed or approved by IRIS and are used at your sole risk. We make no representation or warranty concerning the enforceability of any agreements signed or exchanged by electronic means through tools or functions made available on or through the Platform.

    **USER SHOULD SEEK LEGAL ADVICE BEFORE UTILIZING OR ENTERING INTO ANY AGREEMENTS OR OTHER DOCUMENTS OR RELYING ON ANY INFORMATION MADE AVAILABLE THROUGH THE PLATFORM. IRIS DOES NOT PROVIDE LEGAL ADVICE OR ANY ADVICE CONCERNING ANY LEGAL DOCUMENTS OFFERED BY A USER TO ANOTHER USER, INCLUDING PROJECT AGREEMENTS.**

4. **Applicable Laws.** You agree that you are responsible for, and agree to abide by, all laws, rules, and regulations applicable to your use of the Platform, your use of any tool, service or product offered on the Platform and any transaction or agreement you enter into on the Platform or in connection with your use of the Platform. You further agree that you are responsible for and agree to abide by all laws, rules and regulations applicable to the Project, including any and all laws, rules, regulations or other requirements relating to taxes, credit cards, data and privacy, accessibility, and compliance with all anti-discrimination laws, as applicable.
5. **Compliance with Government Investigations.** You acknowledge that, even though we are not a party to any Project Agreement, unless otherwise stated in a particular Project Agreement, and we assume no liability for legal or regulatory compliance pertaining to any Project listed on the Platform, there may be circumstances where we are nevertheless legally obligated (as we may determine in our sole discretion) to provide information relating to your Project in order to comply with governmental bodies in relation to investigations, litigation or administrative proceedings. We may choose to comply with or disregard such obligation in our sole discretion.
6. **Payments.** Any payments between Users are for services provided by Consultants or another party separate from IRIS. Payment amounts are determined solely between Users. While IRIS provides the Platform through which activities are facilitated, IRIS is not liable for, party to, or responsible for those transactions, even though IRIS may receive a commission from such payments and assist in the administration of remuneration from Project Proponents to Consultants. User agrees that issues or concerns, including non-receipt of payment, any discrepancy in payment amounts, or delays in payment, will be addressed by contacting the relevant User or third party.

## ACCESS AND USE OF THE PLATFORM

1. **Registration.** If you choose to register for the Platform, you agree to provide and maintain true, accurate, current and complete information about yourself as prompted by the Platform’s registration form to create your user account, including your name or the name of the organization you represent, email address, password and phone number (“**Personal Contact Information**”). If you are under 13 years of age, you are not authorized to use the Platform, with or without registering. In addition, if you are under 18 years old, you may use the Platform, with or without registering, only with the approval and supervision of your parent or guardian. In addition, you may also provide certain additional information in order to enable the Platform to match you to appropriate Projects, including information pertaining to location, identity, disabilities you identify with, citizenship status (“**Demographic Information**”, together with Personal Contact Information, the “**Registration Information**”). If you provide any Personal Contact Information or Demographic Information that is untrue, inaccurate, not current, or incomplete, or if IRIS has a reasonable ground to suspect that such information is untrue, inaccurate, not current, or incomplete, IRIS has the right, in its sole discretion, to suspend or terminate your account and refuse any and all current or future use of the Platform (or any portion thereof). If you invite anyone under the age of 18 (an “**Underaged Person**”) to use the Platform, you agree to be solely responsible for the Underaged Person’s use of same.
2. **Password and Security.** You are responsible for maintaining the confidentiality of your Registration Information (and the Registration Information of related usernames) and are fully responsible for any and all activities that occur under your user account or related to your Personal Contact Information. You agree to (a) immediately notify IRIS of any unauthorized use of your Registration Information or any other breach of security, and (b) ensure that you log out from the Platform at the end of each session when accessing the Platform. IRIS will not be liable for any loss or damage arising from your failure to comply with this Subsection 3(b). Further, you agree not to allow third parties to access the Platform or IRIS’ website through your username and password.
3. **Modification of the Platform.** IRIS reserves the right to modify the form and nature of the Platform, or discontinue, temporarily or permanently, the Platform (or any part thereof) with or without notice. You agree that IRIS will not be liable to you or to any third party for any modification, suspension or discontinuance of the Platform. IRIS may also, in its sole discretion, restrict access to the website for any reason.
4. **General Practices.** You acknowledge that IRIS may establish general practices and limits concerning use of the Platform, including, without limitation, the maximum period of time that data or other content will be retained by the Platform and the maximum storage space that will be allotted on IRIS’ or its partners’, affiliates’, or service providers’ servers on your behalf. You agree that IRIS has no responsibility or liability for the deletion or failure to store any data or other content maintained or Uploaded by the Platform. You acknowledge that IRIS reserves the right to terminate accounts that are inactive for an extended period of time. You further acknowledge that IRIS reserves the right to change these general practices and limits at any time, in its sole discretion, with or without notice.
5. **Platform Access.** In order to use the Platform, you must obtain Internet access, either directly or through devices that access web-based content and pay any service fees associated with such access. You are solely responsible for paying such fees. In addition, you must provide all equipment necessary to make such Internet connection, including a computer and modem or other access device. You are solely responsible for providing such equipment. You acknowledge that while IRIS may not currently have set a fixed upper limit on the number of transmissions you may send or receive through the Platform or on the amount of storage space used for the provision of the Platform’s services, such fixed upper limits may be set by IRIS at any time, at IRIS’ discretion.

## PRIVACY AND CONFIDENTIALITY

IRIS respects your right to privacy. Any Personal Contact Information or Demographic Information collected in connection with your registering on and use of the Platform shall be done in accordance with [IRIS’ Privacy Policy](:privacy_policy),which forms part of these Terms. User is responsible for its compliance with all applicable privacy laws and covenants. User must ensure that all personal data and information provided to IRIS or Uploaded to the Platform is provided in compliance with applicable laws.

## SECURITY

IRIS has implemented security policies and practices that are designed to protect the security and integrity of the Platform; however, IRIS does not guarantee the security of the Platform or the security or integrity of any communications between you and the Platform. You acknowledge that you alone are responsible for ensuring you have a secure connection to access the Platform and implementing security safeguards to protect yourself when accessing and using the Platform, including taking precautions against viruses, worms, trojan horses and other items of a disabling or destructive nature.

## CONDITIONS OF USE

1. **Unauthorized uses of the Platform.** You agree not to:
    1. Engage in the commercial use of the Platform except for the purposes set out in these Terms;
    2. interfere with or disrupt the Platform or servers or networks connected to the Platform, or disobey any requirements, procedures, policies or regulations of networks connected to the Platform; or violate any applicable provincial, territorial, local, national or international law, or any regulations having the force of law;
    3. modify, copy, reproduce, reverse engineer, frame, rent, lease, loan, sell, distribute, publish, or create derivative works based on the Platform or the Service Content (as defined below), in whole or in part;
    4. engage in or use any data mining, robots, scraping or similar data gathering or extraction methods;
    5. collect, aggregate, copy, scrape, duplicate, display or derivatively use the Platform;
    6. transmit any viruses, worms, defects, Trojan horses, or other items of a destructive nature;
    7. implement any measures to circumvent any tools or resources IRIS has used to block you from accessing all or some of the Platform (e.g., by masking your IP address or using a proxy IP address);
    8. impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;
    9. solicit personal information from any Underaged Person; or harm such persons in any way;
    10. harvest or collect email addresses or other contact information of other users from the Platform by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications;
    11. advertise or offer to sell or buy any goods or services for any business purpose that is not specifically authorized;
    12. further or promote any criminal activity or enterprise or provide instructional information about illegal or potentially illegal activities;
    13. obtain or attempt to access or otherwise obtain any materials or information through any means not intentionally made available or provided for through the Platform;
    14. add your own headers, forge headers, or otherwise manipulate identifiers in a manner not permitted by the Platform, in order to disguise the origin of any User Content transmitted through the Platform;
    15. "stalk" or otherwise harass another person;
    16. use any information received through the Platform to attempt to identify other Users, to contact other Users (other than through features for contacting other Users), or for any forensic use;
    17. download any file posted by another User of the Platform that you know, or reasonably should know, cannot legally be distributed in such manner;
    18. violate these Terms, any code of conduct or other guidelines which may be applicable for any particular area of the Platform, including those that have been communicated to you by anyone affiliated with IRIS; or
    19. violate any of the obligations contained in these Terms, including, but not limited to, those contained in Section 9 hereof pertaining to intellectual property rights.
2. **Invoices.** IRIS will invoice Project Proponents the annual subscription amount owed to access and use the Platform. Project Proponents hereby agree to pay any undisputed amounts to IRIS within thirty (30) days of such invoice.
3. **Suspension.** You acknowledge and agree that you are solely responsible for (and that IRIS has no responsibility to you or to any third party for) any breach of your obligations under these Terms or for the consequences (including any loss or damage which IRIS may suffer) of any such breach. If you breach these Terms and/or IRIS has a reasonable ground to suspect that you have violated the terms of these Terms, IRIS may suspend or terminate your access to and use of the Platform (or any portion thereof).

## USER CONTENT

1. You are solely responsible for all Content that you Upload or make available to IRIS (“**User Content**”).
2. You acknowledge that IRIS does not independently evaluate, investigate, or otherwise conduct any due diligence regarding any User Content provided by other Users and IRIS has no liability to User for any damage or loss concerning the accuracy of User Content or User’s access to, or use of, or reliance on, any User Content.
3. User represents and warrants that all User Content made available to and through the Platform: (i) is true, accurate and current; (ii) belongs to User and that User owns all right, title and interest in and to such User Content, including, without limitation, all copyrights and rights of publicity contained therein; (iii) does not and will not, directly or indirectly, infringe, violate or breach any duty toward or rights of any person or entity, including without limitation any copyright, trademark, service mark, trade secret, other intellectual property, publicity or privacy right; (iv) is provided in compliance with all applicable laws, regulations, regulatory guidelines, policies and codes and industry guidelines, policies and codes.
4. You agree not to Upload any Content that (1) infringes any intellectual property or other proprietary rights of any party, (2) constitutes inside information, proprietary or confidential information, under any law, contractual or fiduciary relationship, or Content that was learned or disclosed as part of employment relationships or under nondisclosure agreements, (3) contains malicious software code, including viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment, (4) poses or creates a privacy or security risk to the platform or any person, (5) constitutes unsolicited or unauthorized advertising, promotional materials, commercial activities and/or sales, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” “contests,” “sweepstakes,” or any other form of solicitation, (6) is unlawful, harmful, threatening, abusive, harassing, tortious, excessively violent, defamatory, vulgar, obscene, pornographic, libelous, invasive of another’s privacy, hateful racially, ethnically or otherwise objectionable, or (7) in the sole judgment of IRIS, is objectionable or which restricts or inhibits any other person from using or enjoying the Platform, or which may expose IRIS or its users to any harm or liability of any type.
5. You acknowledge that IRIS and its designees shall have the right (but not the obligation) in their sole discretion to pre-screen, review, filter, modify, refuse, or move any User Content that is available via the Platform. Without limiting the foregoing, IRIS and its designees shall have the right to remove any User Content that violates these Terms or is deemed by IRIS, in its sole discretion, to be otherwise objectionable. IRIS reserves the right to investigate and take appropriate action if, in IRIS’ sole discretion, any User Content Uploaded is illegal or prohibited User Content (including User Content that includes any of the content listed below). Such actions may include without limitation, removing the offending Content from the Platform, suspending or terminating your access to the Platform and reporting you to the law enforcement authorities.

## THIRD PARTY CONTENT AND SERVICES

1. **Third Party Content.** Certain third-party service providers, including advertisers, payment processing vendors, and other service providers (“**Third Party Provider**”) may Upload Content to the Platform (“**Third Party Content**”). IRIS does not control or own, is not responsible for, and does not guarantee the accuracy, integrity, or quality of such Third Party Content. All issues or concerns, technical or otherwise, with Third Party Content must be addressed by contacting the applicable Third Party Provider directly and not through IRIS. Under no circumstances will IRIS be liable in any way for any Third Party Content, including, but not limited to, any errors or omissions in any such Third Party Content, or for any loss or damage of any kind incurred as a result of the use of any such Third Party Content posted, emailed, or otherwise transmitted via the Platform. You acknowledge and agree that you rely on the use of any Third Party Content, at your own risk, including any reliance on the accuracy, completeness, or usefulness of such content.
2. **Third Party Services.** In addition to Third Party Content, the Platform may allow you to connect with Third Party Providers in order to purchase goods and/or sign up for services from, or participate in, promotions of a Third Party (“**Third Party Service”**). You acknowledge and agree that the provision of any Third Party Service is provided solely by the applicable Third Party, and not IRIS, and is subject to the terms and conditions of such Third Party (“**Third Party Terms**”). IRIS is not a party to any Third Party Terms and shall have no liability, obligation, responsibility or duty for any Third Party Service between you and any such Third Party Provider. Your use of any Third Party Service is solely at your risk.
3. **Third Party Payment Processors.** If, as part of the Services, the Platform offers Project Proponents the ability to pay Consultants directly, any such payments will be made using a Third Party Service provided by a Third Party Provider. The processing of payments or credits, as applicable, will be subject to the Third Party Terms of the Third Party Provider and applicable credit card issuer. IRIS is not responsible for any errors by the payment processor and Users will resolve any disputes for amounts charged directly with the payment processor. In connection with Users’ use of the Platform and receipt of Services, IRIS may obtain certain transaction details, which IRIS will only use in accordance with these Terms. Users will be responsible for obtaining all necessary authorizations and consents to process User credit cards and other permitted payment cards and methods.

## INTELLECTUAL PROPERTY RIGHTS

1. **Service Content.** You acknowledge and agree that all right, title, and interest (including all intellectual property rights) in and to the Platform and any Content on the Platform (excluding any User Content and any Third Party Content), including but not limited to graphics, design, compilation, interfaces, computer code, products, software (together, the “**Service Content**”) are and will remain the sole and exclusive property of IRIS or its third party licensors, as applicable. Any rights not expressly granted under these Terms are reserved by IRIS. Any use of the Platform or the Service Content other than as specifically authorized herein is strictly prohibited. To the extent that IRIS identifies any Service Content or other information on the Platform as confidential, you agree that you will not disclose such information without IRIS’ prior written consent.
2. **Trademarks.** The IRIS name and logos and The Accessibility Exchange name and logos are trademarks and business names of the Institute for Research and Development on Inclusion and Society (collectively the “**IRIS Trademarks**”). Other company, product, and service names and logos used and displayed via the Platform are trademarks of their respective owners who may or may not endorse or be affiliated with or connected to IRIS. Nothing in these Terms or on the Platform should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any of the IRIS Trademarks displayed on the Platform without our prior written permission in each instance. All goodwill generated from the use of the IRIS Trademarks will inure to our exclusive benefit.
3. You agree that you shall not remove, obscure, or alter any proprietary rights notices (including copyright and trademark notices) that may be affixed to or contained within the Platform or in or on any Service Content.

## LICENSES

1. **Use of the Platform.** IRIS authorizes you to access and use the Platform solely for the purpose of searching, accessing, downloading and reviewing Platform Content (in print, audio, video or other provided format) for informational purposes only and solely for your own use.
2. **User Content.** IRIS does not claim ownership of any User Content you provide to IRIS (including feedback and suggestions) via the Platform. Unless otherwise specified, you retain copyright and any other rights you already hold over User Content that you create and submit, post, or display on or through the Platform. However, by submitting, posting, or displaying User Content, you give IRIS and its affiliates and their successors and assigns a perpetual, irrevocable, worldwide, royalty-free, fully paid up, sublicensable and non-exclusive license to reproduce, adapt, modify, translate, publish, publicly perform, publicly display, distribute, Upload, store, edit, reformat, otherwise use and create derivative works from any User Content that you submit, post, or display on or through the Platform.
3. **Disclosure of Submissions.** You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information about the Platform (“Submissions”), provided by you to IRIS are non-confidential and IRIS will be entitled to the unrestricted use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you.
4. **Preservation of Content.** You acknowledge and agree that IRIS may preserve User Content and may also disclose User Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal processes, applicable laws or government requests; (b) enforce these Terms; (c) respond to claims that any content violates the rights of third parties; or (d) protect the rights, property, or personal safety of IRIS, its users and the public.

## USER REPRESENTATIONS

1. You understand and agree that your participation in the Platform is entirely voluntary, and that you are under no obligation to agree to these Terms unless you wish to access the Platform.
2. You represent that you are of legal age, as set forth in Subsection 3(a), to use the Platform.
3. You agree to take responsibility for all possible consequences resulting from your sharing with others access to your User Content.
4. You understand and agree that all your Registration Information will be stored in IRIS’ databases and will be processed in accordance with these Terms.
5. You agree that you have the authority, under the laws of the province or jurisdiction in which you reside, to provide these representations. In case of breach of any one of these representations, IRIS has the right to suspend or terminate your account and refuse any and all current or future use of the Platform (or any portion thereof). You hereby agree to defend and indemnify IRIS and its affiliates against any liability, costs, or damages, including reasonable attorneys’ fees, arising out of the breach of the representations.

## INDEMNITY AND RELEASE

1. You agree to release, indemnify and hold IRIS and its affiliates and their officers, employees, directors and agents (collectively, “**Indemnitees**”) harmless from any and all losses, damages, expenses, liability, or costs, including reasonable attorneys’ fees, rights, claims, actions of any kind and injury (including death) arising out of or relating to (i) your access, use and/or misuse of the Platform; (ii) any of your User Content, including any claim by a third party that the display or other use of User Content infringes the intellectual property or other rights of a third party; (iii) your violation of these Terms or your violation of any rights of another; (iv) access and use of your Registration Information by any third parties; (v) any use of your Registration Information by an Underaged Person; or (vi) claims asserted against the Indemnitees by another User or third party arising as a consequence of User’s act, omission or conduct in relation to the use of the Platform and Services, or a Third Party Service, or any activities ancillary thereto.
2. IRIS shall have the right, in its sole discretion, to participate in the defense of any third party claim. User will not, without the prior written approval of IRIS, settle, dispose or enter into any proposed settlement or resolution of any claim (whether having been finally adjudicated or otherwise) brought against User, if such settlement or resolution results in any obligation or liability for or admission of wrongdoing by IRIS.
3. Notwithstanding the foregoing, you will have no obligation to indemnify or hold harmless any Indemnitee from or against any liability, losses, damages or expenses incurred as a result of any action or inaction of such Indemnitee.

## DISCLAIMER OF WARRANTIES

YOUR USE OF THE PLATFORM IS AT YOUR SOLE RISK. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE PLATFORM IS PROVIDED ON AN “AS IS”, “WITH ALL FAULTS” AND “AS AVAILABLE” BASIS AND AT USER’S SOLE RISK. IRIS EXPRESSLY DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IRIS MAKES NO WARRANTY THAT (I) THE PLATFORM WILL MEET YOUR REQUIREMENTS; (II) THE PLATFORM WILL BE UNINTERRUPTED, TIMELY, UNFAILINGLY SECURE, OR ERROR-FREE; (III) INFORMATION OBTAINED FROM YOUR USE OF THE PLATFORM WILL BE ACCURATE, ERROR FREE, RELIABLE, OR MEET THE NEEDS OF OR REQUIREMENTS OF USERS; (IV) WILL ALWAYS BE AVAILABLE, ACCESSIBLE, UNINTERRUPTED, TIMELY, SECURE OR FREE OF MALICIOUS CODE OR VIRUS; (V) INFORMATION OR MATERIALS OBTAINED BY YOU THROUGH THE PLATFORM WILL MEET YOUR EXPECTATIONS.

ANY SERVICE CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE PLATFORM IS DONE AT YOUR OWN DISCRETION AND RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.

NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM IRIS OR THROUGH ACCESS TO OR USE OF THE PLATFORM OR SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS OF SERVICE.

## LIMITATION OF LIABILITY

YOU EXPRESSLY UNDERSTAND AND AGREE THAT IRIS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, OR DAMAGES FOR LOSS OF PROFITS INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF IRIS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO THOSE DAMAGES RESULTING FROM: (I) THE USE OR THE INABILITY TO USE THE PLATFORM; (II) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE PLATFORM; (III) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (IV) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE PLATFORM; (V) ANY ACTION YOU TAKE BASED ON THE INFORMATION YOU RECEIVE IN THROUGH OR FROM PLATFORM; (VI) YOUR FAILURE TO KEEP YOUR PASSWORD OR ACCOUNT DETAILS SECURE AND CONFIDENTIAL; (VII) THE IMPROPER AUTHORIZATION FOR THE PLATFORM BY SOMEONE CLAIMING SUCH AUTHORITY; OR (VIII) ANY OTHER MATTER RELATING TO THE PLATFORM.

IN NO EVENT WILL IRIS’ TOTAL AGGREGATE LIABILITY, FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATED TO THIS AGREEMENT, THE PLATFORM, PLATFORM CONTENT AND ANY SERVICES, WHETHER IN CONTRACT, TORT OR UNDER ANY OTHER THEORY OF LIABILITY, EXCEED THE LESSER OF (I) ANY FEES PAID BY THE USER TO IRIS FOR THE SERVICES DURING [THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE DATE ON WHICH THE CAUSE OF ACTION AROSE; AND (II) SIX  HUNDRED AND TWENTY-FIVE DOLLARS (CDN$625.00)]

SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OR EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS SET FORTH ABOVE MAY NOT APPLY TO YOU OR BE ENFORCEABLE WITH RESPECT TO YOU.

IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE PLATFORM OR WITH THESE TERMS OF SERVICE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USE OF THE PLATFORM.

## USER DISPUTES

You agree that you are solely responsible for your interactions with any other User in connection with the Platform and that IRIS will have no liability or responsibility with respect thereto. IRIS reserves the right, but has no obligation, to become involved in any way with disputes between you and any other User of the Platform.

## TERMINATION

1. **Term.** This Agreement will continue for a term of twelve (12) months and automatically renew at the end of such period, subject to your continued payment of any subscription amounts owed.
2. **For Cause.** IRIS may, in its sole discretion, immediately terminate these Terms or, without limiting its other rights and remedies, suspend User’s access to the Platform and Services if User fails to comply with any provision of these Terms. In the event that IRIS terminates or suspends your access to the Platform or Services or these Terms under this Section, you understand and agree that you will not receive a refund of, or credit for, any fees paid.
3. **Other Termination.** IRIS reserves the right to terminate these Terms, suspend or terminate User’s access to the Platform and/or any Services with or without notice, or deactivate or delete your account including all related User information for any reason, including:
    1. for lack of use;
    2. if IRIS is required to do so by law (for example, where the provision of the Platform to you is, or becomes, unlawful);
    3. if IRIS is transitioning to no longer providing the Platform to users in the region or province in which you reside or from which you use the Platform; or
    4. if the provision of the Platform to you by IRIS is, in IRIS’ opinion, no longer commercially or financially viable.

    In the event that IRIS terminates or suspends the User’s access to the Services or this Agreement under this Subsection 16(c), User will receive a pro-rata refund of any prepaid fees paid to IRIS for which Services have not been provided. IRIS shall not be liable to you or to any third party for: (i) any suspension or discontinuance of the Services or the Platform, including on account of any expenditures or investments or other commitments made, or actions taken, in reliance on the expected continuation of the Services or Platform; or (ii) any suspected fraudulent, abusive or illegal activity that may be grounds for termination of your use of the Platform and may be referred to appropriate law enforcement authorities.

4.  **Termination for Convenience.** You may terminate these Terms for convenience upon 30 days prior written notice to IRIS. At the end of such 30-day period, IRIS will de-activate your account and to the extent there are outstanding amounts owed from you or to you, either invoice you for any outstanding amounts owed or provide a pro-rata reimbursement of your annual subscription.

## SURVEYS

IRIS desires to continually improve the Platform or Services and may, in accordance with the IRIS Privacy Policy, contact you regarding your use of the Platform or Services. IRIS may also contact you about other studies it has conducted, is conducting, or may conduct in the future, or other services it offers or may offer in the future.

## GENERAL

1. **Entire Agreement.** These Terms constitute the entire agreement between you and IRIS and govern your use of the Platform, superseding any prior agreements between you and IRIS with respect to the Platform. You may also be subject to additional terms and conditions that may apply when you use affiliate or Third Party Services, Third Party Content or third party software.
2. **Language.** The user acknowledges that a French version of these Terms and related documents have been provided to the user and that the user has opted to be bound by the English version.
3. **Governing Law.** These Terms will be governed by the laws of the Province of Ontario without regard to its conflict of law provisions. With respect to any disputes or claims not subject to arbitration, as set forth above, you and IRIS agree to submit to the personal and exclusive jurisdiction of the province of Ontario. The failure of IRIS to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision. Recognizing the global nature of the Internet, you agree to comply with all local rules and laws regarding your use of the Platform, including as it concerns online conduct and acceptable content.
4. **Severability.** If any provision of these Terms is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of these Terms remain in full force and effect.
5. **Limitation Period.** You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Platform or these Terms must be filed within one (1) year after such claim or cause of action arose or be forever barred.  A printed version of this agreement and of any notice given in electronic form will be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.
6. **Assignment.** You may not assign these Terms without the prior written consent of IRIS, but IRIS may assign or transfer these Terms, in whole or in part, without restriction.
7. **Interpretation.** The section titles in these Terms are for convenience only and have no legal or contractual effect.
8. **Waiver.** No failure or delay by IRIS in exercising any right hereunder will waive any further exercise of that right.
9. **Notices.** All notices or approvals required or permitted under these Terms will be in writing and delivered by email transmission, and in each instance will be deemed given upon receipt. All notices or approvals will be sent to IRIS at (<:email>) to you may be made via either email or regular mail. The Platform may also provide notices to you of changes to these Terms or other matters by displaying notices or links to notices generally on the Platform.
10. **Modification.** We reserve the right, at our sole discretion, to change or modify portions of these Terms at any time. If we do this, we will post the changes on [The Accessibility Exchange](:home)  and will indicate at the top of the Terms page the date these terms were last revised. We will also endeavor to notify you, either through the Platform user interface, in an email notification or through other reasonable means. Any such changes will become effective no earlier than fourteen (14) days after they are posted, except that changes addressing new functions of the Platform or changes made for legal reasons will be effective immediately. Your continued use of the Platform after the date any such changes become effective constitutes your acceptance of the new Terms.

## QUESTIONS

If you have any questions, you understand that you may contact IRIS via email at [<:email>].
                ',
                'content->fr' => '
Veuillez lire attentivement ces conditions d’utilisation.

L’Institut de recherche et développement sur l’inclusion et la société (**« l’IRIS »**, **« nous »**, **« notre »** ou **« nos »**) vous invite (**« vous »** ou **« votre »**) à rejoindre le Connecteur pour l’accessibilité (« The Accessibility Exchange » en anglais), une plateforme permettant aux diverses personnes en situation de handicap, aux personnes sourdes et à leurs proches, ainsi qu’aux organisations communautaires, de se connecter les uns aux autres, aux industries et milieux de travail sous réglementation fédérale (**« Industries réglementées »**) et à d’autres organisations (ensemble avec les **Industries réglementées**, les **« Promoteurs de projet »**) dans le but d’élaborer des plans sur l’accessibilité ou d’autres services connexes. Vous pouvez accéder au Connecteur pour l’accessibilité à l’adresse [<:home>] ou sur nos applications mobiles (la **« Plateforme »**). Les présentes conditions d’utilisation et la politique de confidentialité de l’IRIS (ensemble, les **« Conditions »**) régissent votre utilisation de la Plateforme et constituent un accord contractuel juridiquement contraignant entre vous et l’IRIS.

En cliquant pour accepter les Conditions ou en utilisant la Plateforme, vous acceptez d’être lié par ces Conditions.

{.toc .ignore-counter}
## Table des matières

1. [DÉFINITIONS](#définitions)
2. [L’IRIS N’EST PAS PARTIE PRENANTE À UN PROJET OU À UNE ENTENTE DE PROJET, SAUF INDICATION CONTRAIRE EXPLICITE](#liris-nest-pas-partie-prenante-à-un-projet-ou-à-une-entente-de-projet-sauf-indication-contraire-explicite)
3. [ACCÈS ET UTILISATION DE LA PLATEFORME](#accès-et-utilisation-de-la-plateforme)
4. [VIE PRIVÉE ET CONFIDENTIALITÉ](#vie-privée-et-confidentialité)
5. [SÉCURITÉ](#sécurité)
6. [CONDITIONS D’UTILISATION](#conditions-dutilisation)
7. [CONTENU UTILISATEUR](#contenu-utilisateur)
8. [CONTENU ET SERVICES TIERS](#contenu-et-services-tiers)
9. [DROITS DE PROPRIÉTÉ INTELLECTUELLE](#droits-de-propriété-intellectuelle)
10. [LICENCES](#licences)
11. [REPRÉSENTATIONS DES UTILISATEURS](#représentations-des-utilisateurs)
12. [INDEMNISATION ET DÉCHARGE](#indemnisation-et-décharge)
13. [EXCLUSION DE GARANTIE](#exclusion-de-garantie)
14. [LIMITATION DE LA RESPONSABILITÉ](#limitation-de-la-responsabilité)
15. [DIFFÉRENDS ENTRE UTILISATEURS](#différends-entre-utilisateurs)
16. [RÉSILIATION](#résiliation)
17. [SONDAGES ET ÉTUDES](#sondages-et-études)
18. [GÉNÉRAL](#général)
19. [QUESTIONS](#questions)

## DÉFINITIONS

1. L’expression **« Consultant en matière d’accessibilité »** désigne une personne ou une organisation qui aide les Promoteurs de projet à concevoir, faciliter et achever leurs projets.
2. L’expression **« Connecteur communautaire »** désigne une personne ou une organisation qui facilite la mise en relation des Promoteurs de projets avec des communautés, sachant que les Promoteurs de projets cherchent à obtenir des informations sur la manière de s’engager avec la communauté ou les participants lors de consultations et/ou à les soutenir.
3. L’expression **« Participant à la consultation »** désigne une personne ou organisation participant aux consultations organisées par les Promoteurs de projet.
4. L’expression **« Consultant »** désigne un Consultant en matière d’accessibilité, un Connecteur communautaire, ou un Participant à la consultation, selon le contexte.
5. On entend par **« Contenu »** tous documents, y compris les ententes ou les protocoles d’entente, tout codes, liens, vidéos, images, informations, données, textes, logiciels, musique, sons, photographies, graphiques, messages, informations financières, affichages, fichiers, l’identification, données sur les mots clés, ainsi que tout autre contenu publicitaire, informations ou matériels.
6. Les **« Informations démographiques »** ont la signification indiquée à la section 3(a) des présentes Conditions.
7. L’expression **« Industries réglementées »** désigne le premier paragraphe des présentes Conditions.
8. L’expression **« Personne indemnisée »** a la signification qui lui est donnée à la section 12(a) des présentes Conditions.
9. La **« Politique de confidentialité de l’IRIS »** a la signification indiquée dans la section 4 des présentes Conditions.
10. Les **« Marques déposées par l’IRIS »** ont la signification indiquée à l’article 9(b) des présentes Conditions.
11. Les **« Coordonnées personnelles »** ont la signification indiquée au point 3(a) des présentes Conditions.
12. **« Projet »** : toute consultation visant à élaborer un plan sur l’accessibilité ou à entreprendre d’autres activités visant à améliorer l’accessibilité, entre une personne consultante et un promoteur de projet en vertu d’une entente de projet.
13. Les **« Entente de projet »** ont la signification indiquée à la section 2(b) des présentes Conditions.
14. Les **« Promoteurs de projets »** ont la signification qui leur est donnée dans le premier paragraphe des présentes Conditions.
15. Les **« Informations d’inscription »** ont la signification indiquée à la section 3(a) des présentes Conditions.
16. Le  **« Contenu du service »** a la signification indiquée à l’article 9(a) des présentes Conditions.
17. **« Services »** désigne les services que l’IRIS fournit dans le cadre de la plateforme. Il est entendu que ces services excluent spécifiquement les services tiers ou les services fournis par les Consultants en matière d’accessibilité, les Connecteurs communautaires ou les Participants aux consultations.
18. Les **« Rétroactions »** ont la signification indiquée à l’article 10(c) des présentes Conditions.
19. **« Contenu tiers »** a la signification indiquée à l’article 8(a) des présentes Conditions.
20. Le terme **« Fournisseur tiers »** a la signification indiquée à l’article 8(a) des présentes Conditions.
21. **« Service tiers »** a la signification indiquée à l’article 8(b) des présentes Conditions.
22. Les **« Conditions applicables aux tiers »** ont la signification indiquée à l’article 8(b) des présentes Conditions.
23. **« Personne mineure »** a la signification qui lui est donnée à l’article 3(a) des présentes Conditions.
24. **« Téléverser »** signifie envoyer, téléverser, afficher ou publier sur la plateforme.
25. On entend par **« utilisateur »** ou **« vous »** un promoteur de projet ou une personne consultante, selon ce que les circonstances peuvent indiquer ou exiger.
26. Le **« Contenu utilisateur »** a la signification indiquée à l’article 7(a) des présentes Conditions.

## L’IRIS N’EST PAS PARTIE PRENANTE À UN PROJET OU À UNE ENTENTE DE PROJET, SAUF INDICATION CONTRAIRE EXPLICITE

1. **La plateforme est un lieu de rencontre**. La plateforme sert de lieu de rencontre qui :
    1. fournit des outils numériques aux Promoteurs de projets pour leur permettre de proposer des projets et d’entrer en relation avec des Consultants qui peuvent les assister dans la conception et le développement de ces projets ; et
    2. fournit des outils numériques permettant aux Consultants de faire connaître leurs services, d’établir des relations avec les promoteurs de projets et de contribuer à la conception et au développement des projets.

    **L’UTILISATION DE LA PLATEFORME, DE TOUT CONTENU DU SERVICE ET DES SERVICES SE FAIT À LA DISCRÉTION ET AUX RISQUES DE L’UTILISATEUR.**

2. **Projets et ententes de projet**. L’IRIS n’est pas parti aux ententes, transactions, projets ou arrangements (**« Ententes de projet »**) conclus entre les promoteurs de projet et les Consultants, sauf accord explicite. Bien que l’IRIS fournisse la Plateforme et les services vous permettant de vous impliquer dans des projets et de faciliter le paiement de certains services, l’IRIS n’est pas impliqué de quelque manière que ce soit dans le projet autre que par la fourniture des services, et l’IRIS n’est pas non plus partie aux ententes de projet, à l’exception de toute transaction pour les services expressément conclue entre l’IRIS et les utilisateurs. Vous comprenez et acceptez que l’IRIS ne sera en aucun cas responsable du Contenu ou de l’application de toute entente de projet entre vous et un autre utilisateur, le cas échéant. Vous comprenez et acceptez également que, bien que l’IRIS exige des utilisateurs qu’ils soumettent des informations vraies, précises, à jour et complètes, l’IRIS ne peut pas garantir les qualifications d’un Consultant ou le succès d’un projet.
3. **Clause de non-responsabilité**. Tous les avis, les ententes de projet et les documents connexes mis à disposition sur ou via la Plateforme, soit par l’IRIS, soit par d’autres utilisateurs, soit générés en tant que Service tiers sur ou via la Plateforme, ne sont pas légalement examinés, approuvés ou avalisés par l’IRIS et sont utilisés à vos risques et périls. Nous ne faisons aucune déclaration ni ne donnons aucune garantie quant au caractère exécutoire des ententes signées ou échangées par voie électronique au moyen d’outils ou de fonctions mis à disposition sur ou par l’intermédiaire de la Plateforme.

**L’UTILISATEUR DEVRAIT DEMANDER UN AVIS JURIDIQUE AVANT D’UTILISER OU DE CONCLURE DES ENTENTES OU D’AUTRES DOCUMENTS OU DE SE FIER À TOUTE INFORMATION MISE À DISPOSITION PAR LE BIAIS DE LA PLATEFORME. L’IRIS NE FOURNIT PAS DE CONSEILS JURIDIQUES NI DE CONSEILS CONCERNANT LES DOCUMENTS JURIDIQUES PROPOSÉS PAR UN UTILISATEUR À UN AUTRE UTILISATEUR, Y COMPRIS LES ENTENTES DE PROJET**.

4. **Lois applicables**. Vous acceptez de respecter et de suivre toutes les lois, règles et réglementations applicables à votre utilisation de la Plateforme, à votre utilisation de tout outil, service  ou produit offert sur la Plateforme et à toute transaction ou entente que vous concluez sur la Plateforme ou en relation avec votre utilisation de la Plateforme. Vous acceptez en outre de respecter toutes les lois, règles et réglementations applicables aux projets, y compris toutes les lois, règles, réglementations ou autres exigences relatives aux impôts, aux cartes de crédit, aux données et à la vie privée, à l’accessibilité et au respect de toutes les lois antidiscriminatoires, le cas échéant.
5. **Conformité avec les enquêtes gouvernementales**. Vous reconnaissez que, même si nous ne sommes pas parties à une entente de projet, sauf indication contraire dans une entente de projet spécifique, et que nous n’assumons aucune responsabilité en matière de conformité légale ou réglementaire relative à un projet répertorié sur la Plateforme, il peut y avoir des circonstances dans lesquelles nous sommes néanmoins légalement obligés (comme nous pouvons le déterminer à notre seule discrétion) de fournir des informations relatives à votre projet afin de nous conformer à des organismes gouvernementaux dans le cadre d’enquêtes, de litiges ou de procédures administratives. Nous pouvons choisir de nous conformer à cette obligation ou de l’ignorer à notre seule discrétion.
6. **Paiements**. Tout paiement entre les utilisateurs porte sur des services fournis par des Consultants ou une autre partie distincte de l’IRIS. Les montants des paiements sont déterminés uniquement entre les utilisateurs. Bien que l’IRIS fournisse la Plateforme par laquelle les activités sont facilitées, l’IRIS n’est pas responsable de ces transactions, et ce, même si l’IRIS peut recevoir une commission sur ces paiements et aider à l’administration de la rémunération des Promoteurs de projets aux Consultants. L’utilisateur accepte que les problèmes ou les préoccupations, y compris la non-réception d’un paiement, toute divergence dans les montants de paiement ou les retards de paiement, soient traités en contactant l’utilisateur ou le tiers concerné. [IRIS : Confirmer si les informations bancaires collectées lors de l’inscription]

## ACCÈS ET UTILISATION DE LA PLATEFORME

1. **Informations relatives à l’inscription**. Si vous choisissez de vous inscrire sur la Plateforme, vous acceptez de fournir et de maintenir à jour des informations vraies, exactes et complètes sur vous-même, comme vous y invite le formulaire d’inscription de la Plateforme pour créer votre compte d’utilisateur, y compris votre nom ou le nom de l’organisation que vous représentez, votre adresse électronique, votre mot de passe et votre numéro de téléphone (**« Informations de contact personnelles »**). Si vous avez moins de 13 ans, vous n’êtes pas autorisé à utiliser la Plateforme, avec ou sans inscription. En outre, si vous avez moins de 18 ans, vous ne pouvez utiliser la Plateforme, avec ou sans inscription, qu’avec l’accord et sous la surveillance de vos parents ou de votre tuteur légal. En outre, vous pouvez également fournir certaines informations supplémentaires afin de permettre à la Plateforme de vous mettre en relation avec des projets appropriés, y compris des informations relatives à votre emplacement géographique, à l’identité ou aux handicaps auxquels vous vous identifiez, à votre statut de citoyenneté ou d’immigration au Canada(**« Informations démographiques »**, avec les coordonnées personnelles, les **« Informations d’inscription»**). Si vous fournissez des Informations de contact personnelles ou des Informations démographiques fausses, inexactes, périmées ou incomplètes, ou si l’IRIS a de bonnes raisons de soupçonner que ces informations sont fausses, inexactes, périmées ou incomplètes, l’IRIS a le droit, à sa seule discrétion, de suspendre ou de résilier votre compte et de vous refuser toute utilisation actuelle ou future de la Plateforme (ou d’une partie de celle-ci). Si vous invitez une personne âgée de moins de 18 ans (une **« Personne mineure »**) à utiliser la Plateforme, vous convenez d’assumer l’entière responsabilité de l’utilisation de la Plateforme par ladite Personne mineure.
2. **Mot de passe et sécurité**. Vous êtes responsable du maintien de la confidentialité de vos Informations d’inscription (et des Informations d’inscription des noms d’utilisateur associés) et vous êtes entièrement responsable de toutes les actions posées par  votre compte d’utilisateur ou qui sont liées à vos coordonnées personnelles. Vous acceptez de (a) notifier immédiatement l’IRIS de toute utilisation non autorisée de vos Informations d’inscription ou de toute autre violation de la sécurité, et (b) de vous assurer que vous vous déconnectez de la Plateforme à la fin de chaque session lorsque vous accédez à la Plateforme. L’IRIS ne sera pas responsable des pertes ou dommages résultant du non-respect de la présente sous-section 3(b). En outre, vous acceptez de ne pas permettre à des tiers d’accéder à la Plateforme ou au site Internet de l’IRIS par le biais de votre nom d’utilisateur et de votre mot de passe.
3. **Modification de la Plateforme**. L’IRIS se réserve le droit de modifier la forme et la nature de la Plateforme, ou d’interrompre, temporairement ou définitivement, la Plateforme (ou une partie de celle-ci) avec ou sans préavis. Vous acceptez que l’IRIS ne soit pas responsable envers vous ou envers un tiers de toute modification, suspension ou interruption de la Plateforme. L’IRIS peut également, à sa seule discrétion, restreindre l’accès au site Internet pour quelque raison que ce soit.
4. **Pratiques générales**. Vous reconnaissez que l’IRIS peut établir des pratiques générales et des limites concernant l’utilisation de la Plateforme, y compris, sans limitation, la période maximale pendant laquelle les données ou autres Contenus seront conservés par la Plateforme et l’espace de stockage maximal qui sera alloué en votre nom sur les serveurs de l’IRIS ou de ses partenaires, affiliés ou fournisseurs de services. Vous acceptez que l’IRIS ne soit pas responsable de la suppression ou de l’incapacité à stocker des données ou d’autres Contenus conservés ou Téléversés par la Plateforme. Vous reconnaissez que l’IRIS se réserve le droit de résilier les comptes qui sont inactifs pendant une période prolongée. Vous reconnaissez également que l’IRIS se réserve le droit de modifier ces pratiques et limites générales à tout moment, à sa seule discrétion, avec ou sans préavis.
5. **Accès à la Plateforme**. Pour utiliser la Plateforme, vous devez avoir accès à Internet, soit directement, soit par l’intermédiaire d’appareils permettant d’accéder à du Contenu basé sur Internet, et payer tous les frais de service associés à cet accès. Vous êtes seul responsable du paiement de ces frais. En outre, vous devez fournir tout l’équipement nécessaire pour établir cette connexion Internet, y compris un ordinateur et un modem ou tout autre dispositif d’accès. Vous êtes seul responsable de la fourniture de cet équipement. Vous reconnaissez que, bien que l’IRIS n’ait pas encore fixé de limite supérieure au nombre de transmissions que vous pouvez envoyer ou recevoir par l’intermédiaire de la Plateforme ou à l’espace de stockage utilisé pour la fourniture des services de la Plateforme, de telles limites peuvent être fixées par l’IRIS à tout moment, à la discrétion de l’IRIS.

## VIE PRIVÉE ET CONFIDENTIALITÉ

L’IRIS respecte votre droit à la vie privée. Toutes les coordonnées personnelles ou Informations démographiques collectées dans le cadre de votre inscription et de votre utilisation de la Plateforme doivent être conformes à la [Politique de confidentialité d’IRIS](:privacy_policy), qui fait partie intégrante des présentes Conditions. L’utilisateur est responsable du respect de toutes les lois et conventions applicables en matière de protection de la vie privée. L’utilisateur doit s’assurer que toutes les données et renseignements personnels fournis à l’IRIS ou Téléversées sur la Plateforme le sont en conformité avec les lois applicables.

## SÉCURITÉ

L’IRIS a mis en œuvre des politiques et des pratiques de sécurité conçues pour protéger la sécurité et l’intégrité de la Plateforme ; toutefois, l’IRIS ne garantit pas la sécurité de la Plateforme ni la sécurité ou l’intégrité des communications entre vous et la Plateforme. Vous reconnaissez que vous êtes seul responsable de vous assurer que vous disposez d’une connexion sécurisée pour accéder à la Plateforme et de mettre en œuvre des mesures de sécurité pour vous protéger lorsque vous accédez à la Plateforme et l’utilisez, notamment en prenant des précautions contre les virus, les vers, les chevaux de Troie et autres éléments de nature invalidante ou destructrice.

## CONDITIONS D’UTILISATION

1. **Utilisations non autorisées de la Plateforme**. Vous acceptez de ne pas :
    1. faire un usage commercial de la Plateforme, sauf aux fins énoncées dans les présentes Conditions ;
    2. interférer avec/perturber le fonctionnement de la Plateforme ou des serveurs ou réseaux connectés à la Plateforme; désobéir à toute exigence, procédure, politique ou réglementation des réseaux connectés à la Plateforme ; violer toute loi provinciale, territoriale, locale, nationale ou internationale applicable, ou toute réglementation ayant force de loi ;
    3. modifier, copier, reproduire, effectuer une rétro-ingénierie, louer, prêter, vendre, distribuer, publier ou créer des œuvres dérivées basées sur la Plateforme ou le Contenu des services (tels que définis ci-dessous), en tout ou en partie ;
    4. vous engager dans ou d’utiliser des méthodes d’exploration de données, des robots, des aspirateurs (ou scrapers) de site ou de Contenu ou des méthodes similaires de collecte ou d’extraction de données ;
    5. collecter, agréger, copier, rechercher, dupliquer, afficher ou utiliser la Plateforme de manière dérivée ;
    6. transmettre des virus, des vers, des chevaux de Troie ou d’autres éléments de nature destructrice ;
    7. mettre en œuvre des mesures visant à contourner les outils ou ressources utilisés par l’IRIS pour vous empêcher d’accéder à tout ou à une partie de la Plateforme (par exemple, en masquant votre adresse IP ou en utilisant une adresse IP proxy) ;
    8. usurper l’identité d’une personne ou d’une organisation, ou déclarer faussement ou présenter de manière erronée votre affiliation avec une personne ou une organisation ;
    9. solliciter des renseignements personnels auprès d’une Personne mineure ; ou porter atteinte à ces personnes de quelque manière que ce soit ;
    10. collecter des adresses électroniques ou d’autres Informations de contact d’autres utilisateurs de la Plateforme, par des moyens électroniques ou autres, dans le but d’envoyer des courriers électroniques ou d’autres communications non sollicitées;
    11. faire de la publicité ou proposer de vendre ou d’acheter des biens ou des services à des fins commerciales qui ne sont pas spécifiquement autorisées ;
    12. favoriser ou promouvoir toute activité ou entreprise criminelle ou fournir des informations didactiques sur des activités illégales ou potentiellement illégales ;
    13. obtenir ou tenter d’accéder ou d’obtenir de toute autre manière tout matériel ou information par des moyens qui ne sont pas intentionnellement mis à disposition ou fournis par la Plateforme ;
    14. ajouter vos propres en-têtes, falsifier des en-têtes ou manipuler des identifiants d’une manière non autorisée par la Plateforme, afin de déguiser l’origine de tout Contenu utilisateur transmis par l’intermédiaire de la Plateforme ;
    15. « traquer » ou harceler de toute autre manière une autre personne ;
    16. utiliser toute information reçue par l’intermédiaire de la Plateforme pour tenter d’identifier d’autres utilisateurs, pour contacter d’autres utilisateurs (autrement que par l’intermédiaire de fonctions permettant de contacter d’autres utilisateurs), ou pour tout usage médico-légal ;
    17. télécharger tout fichier publié par un autre utilisateur de la Plateforme dont vous savez, ou devriez raisonnablement savoir, qu’il ne peut être légalement distribué de cette manière ;
    18. violer les présentes Conditions, tout code de conduite ou toute autre directive applicable à une zone particulière de la Plateforme, y compris celles qui vous ont été communiquées par toute personne affiliée à l’IRIS ; ou
    19. violer l’une des obligations contenues dans les présentes Conditions, y compris, mais sans s’y limiter, celles contenues dans la section 9 des présentes Conditions relatives aux droits de propriété intellectuelle.
2. **Factures**. L’IRIS facturera aux promoteurs de projet le montant de l’abonnement annuel dû pour l’accès et l’utilisation de la Plateforme. Les promoteurs de projet acceptent par la présente de payer tout montant non contesté à l’IRIS dans un délai de trente (30) jours à compter de la date de la facture.
3. **Suspension**. Vous reconnaissez et acceptez que vous êtes seul responsable (et que l’IRIS n’a aucune responsabilité envers vous ou envers un tiers) de toute violation de vos obligations en vertu des présentes Conditions ou des conséquences (y compris toute perte ou tout dommage que l’IRIS pourrait subir) d’une telle violation. Si vous enfreignez les présentes Conditions et/ou si l’IRIS a des motifs raisonnables de soupçonner que vous avez enfreint les termes des présentes Conditions, l’IRIS peut suspendre ou résilier votre accès et votre utilisation de la Plateforme (ou d’une partie de celle-ci).

## CONTENU UTILISATEUR

1. Vous êtes seul responsable de tout le Contenu que vous Téléversez ou que vous mettez à la disposition de l’IRIS (**« Contenu utilisateur »**).
2. Vous reconnaissez que l’IRIS n’évalue pas de manière indépendante, n’enquête pas et ne fait pas preuve de diligence raisonnable en ce qui concerne le Contenu utilisateur fourni par d’autres utilisateurs. Vous reconnaissez que l’IRIS n’est pas responsable envers l’utilisateur de tout dommage ou perte concernant l’exactitude du Contenu utilisateur ou l’accès à, l’utilisation ou la confiance accordée à tout Contenu utilisateur.
3. L’utilisateur déclare et garantit que tout le Contenu utilisateur mit à disposition sur et par l’intermédiaire de la Plateforme : (i) est vrai, exact et à jour ; (ii) appartient à l’utilisateur et que l’utilisateur possède tous les droits, titres et intérêts relatifs à ce Contenu utilisateur, y compris, sans limitation, tous les droits d’auteur et droits de publicité qu’il contient ; (iii) n’enfreint pas et n’enfreindra pas, directement ou indirectement, les obligations ou les droits de toute personne ou entité, y compris, mais sans s’y limiter, les droits d’auteur, les marques commerciales, les marques de service, les secrets commerciaux, les autres droits de propriété intellectuelle, les droits de publicité ou de protection de la vie privée ; (iv) est fourni conformément à l’ensemble des lois, réglementations, lignes directrices réglementaires, politiques et codes applicables, ainsi qu’aux lignes directrices, politiques et codes du secteur d’activité.
4. Vous vous engagez à ne pas Téléverser de Contenu qui (1) porte atteinte à la propriété intellectuelle ou à d’autres droits de propriété de toute partie, (2) constitue une information privilégiée, une information exclusive ou confidentielle, en vertu de toute loi, relation contractuelle ou fiduciaire, ou du Contenu qui a été appris ou divulgué dans le cadre de relations de travail ou d’accords de non-divulgation, (3) contient un code logiciel malveillant, y compris des virus ou tout autre code informatique, des fichiers ou des programmes conçus pour interrompre, détruire ou limiter la fonctionnalité de tout logiciel ou matériel informatique ou équipement de télécommunication, (4) pose ou crée un risque pour la vie privée ou la sécurité de la Plateforme ou de toute personne, (5) constitue une publicité non sollicitée ou non autorisée, du matériel promotionnel, des activités commerciales et/ou des ventes, du  « courrier indésirable », du  « spam », des « chaînes de lettres », des « systèmes pyramidaux », des  « concours », des  « loteries » ou toute autre forme de sollicitation, (6) est illégal, nuisible, menaçant, abusif, harcelant, délictueux, excessivement violent, diffamatoire, vulgaire, obscène, pornographique, attentatoire à la vie privée d’autrui, haineux, raciste, xénophobe ou autrement répréhensible, ou (7) qui, selon le seul jugement de l’IRIS, est répréhensible ou qui restreint ou empêche toute autre personne d’utiliser ou de profiter de la Plateforme, ou qui peut exposer l’IRIS ou ses utilisateurs à un préjudice ou à une responsabilité de quelque nature que ce soit.
5. Vous reconnaissez que l’IRIS et ses représentants ont le droit (mais pas l’obligation), à leur seule discrétion, de présélectionner, examiner, filtrer, modifier, refuser ou déplacer tout Contenu utilisateur disponible via la Plateforme. Sans limiter la portée de ce qui précède, l’IRIS et ses représentants auront le droit de supprimer tout Contenu utilisateur qui enfreint les présentes Conditions ou qui est considéré par l’IRIS, à sa seule discrétion, comme répréhensible d’une autre manière. L’IRIS se réserve le droit d’enquêter et de prendre les mesures appropriées si, à la seule discrétion de l’IRIS, tout Contenu utilisateur Téléversé est un Contenu utilisateur illégal ou interdit (y compris du Contenu utilisateur qui comprend l’un des contenus énumérés ci-dessus). Ces actions peuvent inclure, sans s’y limiter, la suppression du Contenu incriminé de la Plateforme, la suspension ou la résiliation de votre accès à la Plateforme et votre signalement aux autorités chargées de l’application de la loi.

## CONTENU ET SERVICES TIERS

1. **Contenu tiers**. Certains fournisseurs de services tiers, y compris des annonceurs, des fournisseurs de traitement des paiements et d’autres fournisseurs de services (**« Fournisseur tiers »**) peuvent Téléverser du Contenu sur la Plateforme (**« Contenu tiers »**). L’IRIS ne contrôle pas, ne possède pas, n’est pas responsable et ne garantit pas l’exactitude, l’intégrité ou la qualité de ce Contenu tiers. Tous les problèmes ou préoccupations, techniques ou autres, concernant le Contenu tiers doivent être abordés en contactant directement le Fournisseur tiers concerné et non par l’intermédiaire de l’IRIS. L’IRIS ne sera en aucun cas responsable du Contenu tiers, y compris, mais sans s’y limiter, de toute erreur ou omission dans ce Contenu tiers, ou de toute perte ou dommage de quelque nature que ce soit résultant de l’utilisation de ce Contenu tiers publié, envoyé par courrier électronique ou transmis de toute autre manière par l’intermédiaire de la Plateforme. Vous reconnaissez et acceptez que vous vous fiez à l’utilisation de tout Contenu tiers, à vos propres risques, y compris en ce qui concerne l’exactitude, l’exhaustivité ou l’utilité d’un tel Contenu.
2. **Services tiers**. Outre le Contenu tiers, la Plateforme peut vous permettre d’entrer en contact avec des Fournisseurs tiers afin d’acheter des biens et/ou de vous inscrire à des services d’un tiers ou de participer à des promotions d’un tiers ( **« Service tiers »**). Vous reconnaissez et acceptez que la fourniture de tout service de tiers est assurée uniquement par le tiers concerné, et non par l’IRIS, et qu’elle est soumise aux Conditions dudit tiers ( **« Conditions du tiers »**). L’IRIS n’est pas parti aux Conditions des tiers et n’a aucune responsabilité, obligation ou devoir pour tout Service tiers entre vous et un tel Fournisseur tiers. L’utilisation d’un Service tiers se fait à vos risques et périls.
3. **Processeurs de paiement tiers**. Si, dans le cadre des services, la Plateforme offre aux promoteurs de projet la possibilité de payer directement les Consultants, ces paiements seront effectués à l’aide d’un Service tiers fourni par un Fournisseur tiers. Le traitement des paiements ou des crédits, selon le cas, sera soumis aux Conditions du Fournisseur tiers et de la société émettrice de la carte de crédit. L’IRIS n’est pas responsable des erreurs commises par le prestataire de services de paiement et les utilisateurs doivent résoudre tout litige concernant les montants facturés directement avec le prestataire de services de paiement. Dans le cadre de l’utilisation de la Plateforme par les utilisateurs et de la réception des services, l’IRIS peut obtenir certains détails de la transaction, que l’IRIS n’utilisera que conformément aux présentes Conditions. Les utilisateurs seront responsables de l’obtention de tous les autorisations et consentements nécessaires pour traiter les cartes de crédit des utilisateurs et les autres cartes et méthodes de paiement autorisées.

## DROITS DE PROPRIÉTÉ INTELLECTUELLE
1. **Contenu du service**. Vous reconnaissez et acceptez que tous les droits, titres et intérêts (y compris tous les droits de propriété intellectuelle) relatifs à la Plateforme et à tout Contenu de la Plateforme (à l’exclusion de tout Contenu utilisateur et de tout Contenu tiers), y compris, mais sans s’y limiter, les graphiques, la conception, la compilation, les interfaces, le code informatique, les produits, les logiciels (ensemble, le **« Contenu du service »**) sont et resteront la propriété unique et exclusive de l’IRIS ou de ses concédants de licence tiers, selon le cas. Tous les droits qui ne sont pas expressément accordés en vertu des présentes Conditions sont réservés par l’IRIS. Toute utilisation de la Plateforme ou du Contenu du service autre que celle spécifiquement autorisée par les présentes Conditions est strictement interdite. Dans la mesure où l’IRIS identifie tout Contenu du service ou toute autre information sur la Plateforme comme étant confidentiel, vous acceptez de ne pas divulguer ces informations sans l’accord écrit préalable de l’IRIS.
2. **Marques commerciales**. Le nom et les logos de l’IRIS et le nom et les logos du Connecteur pour l’accessibilité (**« The Accessibility Exchange »** en anglais) sont des marques commerciales et des noms commerciaux de l’Institut de recherche et développement sur l’inclusion et la société (collectivement les « marques commerciales de l’IRIS ». Les autres noms et logos de sociétés, de produits et de services utilisés et affichés sur la Plateforme sont des marques commerciales de leurs propriétaires respectifs qui peuvent ou non appuyer, être affiliés ou liés à l’IRIS. Rien dans les présentes Conditions ou sur la Plateforme ne doit être interprété comme accordant, par implication, préclusion ou autre, une licence ou un droit d’utilisation de l’une des marques commerciales de l’IRIS affichés sur la Plateforme sans notre autorisation écrite préalable dans chaque cas. Toute la survaleur générée par l’utilisation des marques commerciales d’IRIS sera à notre bénéfice exclusif.
3. Vous acceptez de ne pas supprimer, masquer ou modifier les avis de droits de propriété (y compris les avis de droits d’auteur et de marques) qui peuvent être apposés ou Contenus dans la Plateforme ou dans tout Contenu de service.

## LICENCES
1. **Utilisation de la Plateforme**. L’IRIS vous autorise à accéder à la Plateforme et à l’utiliser uniquement dans le but de rechercher, d’accéder, de télécharger et d’examiner le Contenu de la Plateforme (sous forme imprimée, audio, vidéo ou autre format fourni) à des fins d’information uniquement et pour votre propre usage.
2. **Contenu utilisateur**. L’IRIS ne revendique pas la propriété du Contenu utilisateur que vous fournissez à l’IRIS (y compris les commentaires et les suggestions) via la Plateforme. Sauf indication contraire, vous conservez les droits d’auteur et tous les autres droits que vous détenez déjà sur le Contenu utilisateur que vous créez et soumettez, publiez ou affichez sur ou via la Plateforme. Cependant, en soumettant, postant ou affichant du Contenu utilisateur, vous donnez à l’IRIS et à ses affiliés, ainsi qu’à leurs successeurs et ayants droit, une licence perpétuelle, irrévocable, mondiale, libre de redevances, entièrement payée, sous-licenciable et non exclusive pour reproduire, adapter, modifier, traduire, publier, exécuter publiquement, afficher publiquement, distribuer, télécharger, stocker, éditer, reformater, utiliser autrement et créer des œuvres dérivées à partir de tout Contenu utilisateur que vous soumettez, postez ou affichez sur ou par l’intermédiaire de la Plateforme.
3. **Divulgation de la rétroaction**. Vous reconnaissez et acceptez que toute question, commentaire, suggestion, idée, retour d’information ou autre information concernant la Plateforme (« Rétroaction»), fournie par vous à l’IRIS, est non-confidentielle et que l’IRIS aura le droit d’utiliser et de diffuser sans restriction ces Rétroactions à toutes fins, commerciales ou autres, sans reconnaissance ni compensation pour vous.
4. **Conservation du Contenu**. Vous reconnaissez et acceptez que l’IRIS puisse conserver le Contenu utilisateur et le divulguer si la loi l’exige ou si l’on estime de bonne foi qu’une telle conservation ou divulgation est raisonnablement nécessaire pour : (a) se conformer aux procédures légales, aux lois applicables ou aux demandes du gouvernement ; (b) faire respecter les présentes Conditions ; (c) répondre aux réclamations selon lesquelles un Contenu viole les droits de tiers ; ou (d) protéger les droits, la propriété ou la sécurité personnelle de l’IRIS, de ses utilisateurs et du public.

## REPRÉSENTATIONS DES UTILISATEURS

1. Vous comprenez et acceptez que votre participation à la Plateforme est entièrement volontaire et que vous n’êtes pas obligé d’accepter les présentes Conditions si vous ne souhaitez pas accéder à la Plateforme.
2. Vous déclarez que vous avez l’âge légal, tel que défini au paragraphe 3(a), pour utiliser la Plateforme.
3. Vous acceptez d’assumer la responsabilité de toutes les conséquences possibles résultant du fait que vous partagez avec d’autres l’accès à votre Contenu utilisateur.
4. Vous comprenez et acceptez que toutes vos Informations d’inscription seront stockées dans les bases de données de l’IRIS et seront traitées conformément aux présentes Conditions.
5. Vous convenez que vous avez le pouvoir, en vertu des lois de la province ou de la juridiction dans laquelle vous résidez, de faire ces déclarations. En cas de violation de l’une de ces déclarations, l’IRIS a le droit de suspendre ou de résilier votre compte et de refuser toute utilisation actuelle ou future de la Plateforme (ou d’une partie de celle-ci). Vous acceptez par la présente de défendre et d’indemniser l’IRIS et ses affiliés en cas de responsabilité, de coûts ou de dommages, y compris les frais d’avocat raisonnables, résultant de la violation des déclarations.

## INDEMNISATION ET DÉCHARGE

1. Vous acceptez de libérer, d’indemniser et de tenir l’IRIS et ses affiliés ainsi que leurs dirigeants, employés, administrateurs et agents (collectivement, les **« Personnes indemnisées »**) à l’abri de toute perte, dommage, dépense, responsabilité ou coût, y compris les honoraires raisonnables d’avocat, les droits, les réclamations, les actions de toute nature et les blessures (y compris le décès) découlant de ou liés à (i) votre accès, votre utilisation et/ou votre mauvaise utilisation de la Plateforme ; (ii) votre Contenu utilisateur, y compris toute réclamation d’un tiers selon laquelle l’affichage ou l’utilisation du Contenu utilisateur porte atteinte à la propriété intellectuelle ou à d’autres droits d’un tiers ; (iii) votre violation des présentes Conditions ou votre violation des droits d’un tiers ; (iv) l’accès et l’utilisation de vos Informations d’inscription par des tiers ; (v) toute utilisation de vos Informations d’inscription par une Personne mineure ; ou (vi) les réclamations déposées contre les Personnes indemnisées par un autre utilisateur ou un tiers en conséquence de l’acte, de l’omission ou de la conduite de l’utilisateur dans le cadre de l’utilisation de la Plateforme et des services, ou d’un Service tiers, ou de toute activité connexe.
2. L’IRIS aura le droit, à sa seule discrétion, de participer à la défense de toute réclamation de tiers. L’utilisateur ne doit pas, sans l’accord écrit préalable de l’IRIS, régler, disposer ou s’engager dans une proposition de règlement ou de résolution de toute réclamation (qu’elle ait été définitivement jugée ou non) déposée contre l’utilisateur, si ce règlement ou cette résolution entraîne une obligation ou une responsabilité pour l’IRIS ou l’admission d’un acte répréhensible de sa part.
3. Nonobstant ce qui précède, vous n’aurez aucune obligation d’indemniser ou de dégager de toute responsabilité tout bénéficiaire d’une indemnité en cas de responsabilité, de pertes, de dommages ou de dépenses encourues à la suite d’une action ou d’une inaction de ce bénéficiaire d’une indemnité.

## EXCLUSION DE GARANTIE

L’UTILISATION DE LA PLATEFORME SE FAIT À VOS RISQUES ET PÉRILS. DANS TOUTE LA MESURE PERMISE PAR LA LOI, LA PLATEFORME EST FOURNIE "EN L’ÉTAT", "AVEC TOUS LES DÉFAUTS" ET "TELLE QUE DISPONIBLE" ET AUX SEULS RISQUES DE L’UTILISATEUR. L’IRIS REJETTE EXPRESSÉMENT TOUTE DÉCLARATION ET GARANTIE DE QUELQUE NATURE QUE CE SOIT, EXPRESSE, IMPLICITE OU STATUTAIRE, Y COMPRIS, MAIS SANS S’Y LIMITER, LES GARANTIES ET CONDITIONS IMPLICITES DE QUALITÉ MARCHANDE, D’ADÉQUATION À UN USAGE PARTICULIER, DE TITRE ET D’ABSENCE DE CONTREFAÇON. L’IRIS NE GARANTIT PAS QUE (I) LA PLATEFORME RÉPONDRA À VOS EXIGENCES ; (II) LA PLATEFORME NE CONNAITRA PAS D’INTERRUPTION, QU’ELLE SERA FIABLE, PARFAITEMENT SÉCURISÉE OU EXEMPTE D’ERREURS ; (III) LES INFORMATIONS OBTENUES PAR L’UTILISATION DE LA PLATEFORME SERONT EXACTES, EXEMPTES D’ERREURS, FIABLES OU RÉPONDRONT AUX BESOINS DES UTILISATEURS ; (IV) LA PLATEFORME SERA TOUJOURS DISPONIBLE, ACCESSIBLE, DE FAÇON ININTERROMPUE, OPPORTUNE, SÉCURISÉE OU EXEMPTE DE CODE MALVEILLANT OU DE VIRUS ; (V) LES INFORMATIONS OU LE MATÉRIEL QUE VOUS OBTIENDREZ PAR L’INTERMÉDIAIRE DE LA PLATEFORME RÉPONDRONT À VOS ATTENTES.

TOUT CONTENU DU SERVICE TÉLÉCHARGÉ OU OBTENU D’UNE AUTRE MANIÈRE PAR L’UTILISATION DE LA PLATEFORME L’EST À VOTRE DISCRÉTION ET À VOS RISQUES ET PÉRILS ET VOUS SEREZ SEUL RESPONSABLE DE TOUT DOMMAGE CAUSÉ À VOTRE SYSTÈME INFORMATIQUE OU DE TOUTE PERTE DE DONNÉES RÉSULTANT DU TÉLÉCHARGEMENT D’UN TEL MATÉRIEL.
AUCUN CONSEIL NI AUCUNE INFORMATION, QU’ILS SOIENT ORAUX OU ÉCRITS, OBTENUS PAR VOUS AUPRÈS DE L’IRIS OU PAR LE BIAIS DE L’ACCÈS OU DE L’UTILISATION DE LA PLATEFORME OU DES SERVICES NE PEUVENT CRÉER DE GARANTIE NON EXPRESSÉMENT ÉNONCÉE DANS LES CONDITIONS DE SERVICE.

## LIMITATION DE LA RESPONSABILITÉ

VOUS COMPRENEZ ET ACCEPTEZ EXPRESSÉMENT QUE L’IRIS NE SOIT PAS RESPONSABLE DES DOMMAGES INDIRECTS, ACCESSOIRES, SPÉCIAUX, CONSÉCUTIFS OU PUNITIFS, OU DES DOMMAGES POUR PERTE DE BÉNÉFICES, Y COMPRIS, MAIS SANS S’Y LIMITER, LES DOMMAGES POUR PERTE DE CLIENTÈLE, D’UTILISATION, DE DONNÉES OU D’AUTRES PERTES INTANGIBLES (MÊME SI L’IRIS A ÉTÉ INFORMÉ DE LA POSSIBILITÉ DE TELS DOMMAGES), QU’ILS SOIENT FONDÉS SUR UN CONTRAT, UN DÉLIT, UNE NÉGLIGENCE, UNE RESPONSABILITÉ STRICTE OU AUTRE, Y COMPRIS, MAIS SANS S’Y LIMITER, LES DOMMAGES RÉSULTANT DE : (I) L’UTILISATION OU L’INCAPACITÉ D’UTILISER LA PLATEFORME ; (II) LE COÛT DE L’APPROVISIONNEMENT EN BIENS ET SERVICES DE SUBSTITUTION RÉSULTANT DE TOUS BIENS, DONNÉES, INFORMATIONS OU SERVICES ACHETÉS OU OBTENUS OU DE MESSAGES REÇUS OU DE TRANSACTIONS EFFECTUÉES PAR L’INTERMÉDIAIRE OU À PARTIR DE LA PLATEFORME ; (III) L’ACCÈS NON AUTORISÉ À VOS TRANSMISSIONS OU DONNÉES OU L’ALTÉRATION DE CELLES-CI ; (IV) LES DÉCLARATIONS OU LA CONDUITE DE TOUT TIERS SUR LA PLATEFORME ; (V) TOUTE ACTION QUE VOUS ENTREPRENEZ SUR LA BASE DES INFORMATIONS QUE VOUS RECEVEZ PAR L’INTERMÉDIAIRE OU À PARTIR DE LA PLATEFORME ; (VI) VOTRE INCAPACITÉ À PRÉSERVER LA SÉCURITÉ ET LA CONFIDENTIALITÉ DE VOTRE MOT DE PASSE OU DES DÉTAILS DE VOTRE COMPTE ; (VII) L’AUTORISATION INAPPROPRIÉE DE LA PLATEFORME PAR UNE PERSONNE REVENDIQUANT UNE TELLE AUTORITÉ ; OU (VIII) TOUTE AUTRE QUESTION RELATIVE À LA PLATEFORME.

EN AUCUN CAS LA RESPONSABILITÉ TOTALE DE L’IRIS, POUR TOUTE RÉCLAMATION DÉCOULANT DE OU LIÉE À CET ACCORD, À LA PLATEFORME, AU CONTENU DE LA PLATEFORME ET À TOUT SERVICE, QUE CE SOIT DE MANIÈRE CONTRACTUELLE, DÉLICTUELLE OU EN VERTU DE TOUTE AUTRE THÉORIE DE RESPONSABILITÉ, NE DÉPASSERA LE MOINDRE DE (I) TOUS LES FRAIS PAYÉS PAR L’UTILISATEUR À L’IRIS POUR LES SERVICES AU COURS DE [**LA PÉRIODE DE DOUZE (12) MOIS PRÉCÉDANT IMMÉDIATEMENT LA DATE À LAQUELLE LA CAUSE D’ACTION EST SURVENUE ; ET (II) SIX CENT VINGT-CINQ DOLLARS (CDN$625.00)].

CERTAINES JURIDICTIONS N’AUTORISENT PAS LA RENONCIATION OU L’EXCLUSION DE CERTAINES GARANTIES OU LA LIMITATION OU L’EXCLUSION DE LA RESPONSABILITÉ POUR LES DOMMAGES ACCESSOIRES OU INDIRECTS. PAR CONSÉQUENT, CERTAINES DES LIMITATIONS SUSMENTIONNÉES PEUVENT NE PAS S’APPLIQUER À VOUS OU NE PAS ÊTRE EXÉCUTOIRES À VOTRE ÉGARD.

SI VOUS N’ÊTES PAS SATISFAIT D’UNE PARTIE DE LA PLATEFORME OU DES PRÉSENTES CONDITIONS D’UTILISATION, VOTRE SEUL ET UNIQUE RECOURS CONSISTE À CESSER D’UTILISER LA PLATEFORME.

## DIFFÉRENDS ENTRE UTILISATEURS

Vous acceptez que vous soyez seul responsable de vos interactions avec tout autre utilisateur en relation avec la Plateforme et que l’IRIS n’ait aucune responsabilité à cet égard. L’IRIS se réserve le droit, mais n’a aucune obligation, de s’impliquer de quelque manière que ce soit dans les litiges entre vous et tout autre utilisateur de la Plateforme.

## RÉSILIATION

1. **Durée**. La présente entente contractuelle est conclue pour une durée de douze (12) mois et est automatiquement renouvelée à la fin de cette période, sous réserve que vous continuiez à payer les montants dus au titre de l’abonnement.
2. **Pour cause**. IRIS peut, à sa seule discrétion, résilier immédiatement les présentes Conditions ou, sans limiter ses autres droits et recours, suspendre l’accès de l’utilisateur à la Plateforme et aux services si l’utilisateur ne respecte pas l’une des dispositions des présentes Conditions. Dans le cas où l’IRIS résilie ou suspend votre accès à la Plateforme ou aux services ou aux présentes Conditions en vertu de cette section, vous comprenez et acceptez que vous ne recevrez pas de remboursement ou de crédit pour les frais payés.
3. **Autre résiliation**. L’IRIS se réserve le droit de résilier les présentes Conditions, de suspendre ou de résilier l’accès de l’utilisateur à la Plateforme et/ou aux services avec ou sans préavis, ou de désactiver ou de supprimer votre compte, y compris toutes les informations relatives à l’utilisateur, pour quelque raison que ce soit, y compris :
    1. par manque d ’utilisation ;
    2. si l’IRIS y est contraint par la loi (par exemple, si la mise à disposition de la Plateforme est ou devient illégale) ;
    3. si l’IRIS effectue une transition pour ne plus fournir la Plateforme aux utilisateurs dans la région ou la province/territoire dans lesquelles vous résidez ou à partir desquelles vous utilisez la Plateforme ; ou
    4. si, de l’avis de l’IRIS, la fourniture de la Plateforme par l’IRIS n’est plus commercialement ou financièrement viable.

    Dans le cas où l’IRIS résilie ou suspend l’accès de l’utilisateur aux services ou à la présente entente contractuelle en vertu de la présente sous-section 16(c), l’utilisateur recevra un remboursement au prorata de tous les frais prépayés à l’IRIS pour lesquels les services n’ont pas été fournis. L’IRIS ne sera pas responsable envers vous ou envers un tiers pour : (i) toute suspension ou interruption des services ou de la Plateforme, y compris en raison de dépenses ou d’investissements ou d’autres engagements faits, ou d’actions prises, en se fiant à la continuation attendue des services ou de la Plateforme ; ou (ii) toute activité présumée frauduleuse, abusive ou illégale qui peut être un motif de résiliation de votre utilisation de la Plateforme et peut être transmise aux autorités compétentes chargées de l’application de la loi.

4. **Résiliation pour des raisons de commodité**. Vous pouvez résilier les présentes Conditions pour des raisons de commodité moyennant un préavis écrit de 30 jours adressé à l’IRIS. À la fin de cette période de 30 jours, l’IRIS désactivera votre compte et, dans la mesure où des montants impayés vous sont dus par vous ou à vous, vous facturera les montants impayés ou vous remboursera au prorata de votre abonnement annuel.

## SONDAGES ET ÉTUDES

L’IRIS souhaite améliorer continuellement la Plateforme ou les services et peut, conformément à la politique de confidentialité de l’IRIS, vous contacter au sujet de votre utilisation de la Plateforme ou des services. L’IRIS peut également vous contacter au sujet d’autres études qu’il a menées, qu’il mène ou qu’il pourrait mener à l’avenir, ou au sujet d’autres services qu’il offre ou pourrait offrir à l’avenir.

## GÉNÉRAL

1. **Intégralité de l’entente contractuelle**. Les présentes Conditions constituent l’intégralité de l’entente contractuelle entre vous et l’IRIS et régissent votre utilisation de la Plateforme, remplaçant toute entente antérieure entre vous et l’IRIS concernant la Plateforme. Vous pouvez également être soumis à des conditions supplémentaires qui peuvent s’appliquer lorsque vous utilisez des services affiliés ou de tiers, du Contenu tiers ou des logiciels de tiers.
2. **Langue** L’utilisateur reconnaît avoir reçu une version française des présentes modalités et des documents y afférant et avoir choisi d’être lié par la version anglaise.
3. **Droit applicable**. Les présentes conditions sont régies par les lois de la province de l’Ontario, sans tenir compte des dispositions relatives aux conflits de lois. En ce qui concerne les litiges ou les réclamations non soumis à l’arbitrage, comme indiqué ci-dessus, vous et l’IRIS acceptez de vous soumettre à la juridiction personnelle et exclusive de la province de l’Ontario. Le fait que l’IRIS n’exerce pas ou n’applique pas un droit ou une disposition des présentes Conditions ne constitue pas une renonciation à ce droit ou à cette disposition. Reconnaissant la nature mondiale d’Internet, vous acceptez de vous conformer à toutes les règles et lois locales concernant votre utilisation de la Plateforme, y compris en ce qui concerne la conduite en ligne et le Contenu acceptable.
4. **Divisibilité**. Si une disposition des présentes Conditions est jugée invalide par un tribunal compétent, les parties conviennent néanmoins que le tribunal doit s’efforcer de donner effet aux intentions des parties telles qu’elles ressortent de la disposition, les autres dispositions des présentes Conditions restant pleinement en vigueur.
5. **Délai de prescription**. Vous acceptez qu’indépendamment de tout statut ou loi contraire, toute réclamation ou cause d’action découlant de ou liée à l’utilisation de la Plateforme ou des présentes Conditions doit être déposée dans un délai d’un (1) an après la naissance de ladite réclamation ou cause d’action, sous peine d’être définitivement prescrite. Une version imprimée du présent accord et de tout avis donné sous forme électronique sera admissible dans les procédures judiciaires ou administratives fondées sur le présent accord ou s’y rapportant, dans la même mesure et sous réserve des mêmes Conditions que d’autres documents et dossiers commerciaux générés et conservés à l’origine sous forme imprimée.
6. **Cession**. Vous ne pouvez pas céder les présentes Conditions sans le consentement écrit préalable de l’IRIS, mais l’IRIS peut céder ou transférer les présentes Conditions, en tout ou en partie, sans restriction.
7. **Interprétation**. Les titres des sections des présentes Conditions ne sont donnés qu’à des fins de commodité et n’ont aucun effet juridique ou contractuel.
8. **Renonciation**. Aucun manquement ou retard de la part de l’IRIS dans l’exercice d’un droit en vertu des présentes ne renoncera à l’exercice ultérieur de ce droit.
9. **Avis**. Toutes les notifications ou approbations requises ou autorisées en vertu des présentes Conditions seront formulées par écrit et transmises par courrier électronique et, dans chaque cas, seront réputées donner dès réception. Toutes les notifications ou approbations seront envoyées à l’IRIS à l’adresse (<:email>). Les notifications qui vous sont adressées peuvent être faites soit par courrier électronique, soit par courrier postal. La Plateforme peut également vous fournir des avis sur les modifications apportées aux présentes Conditions ou à d’autres questions en affichant des avis ou des liens vers des avis de manière générale sur la Plateforme.
10. **Modification**. Nous nous réservons le droit, à notre seule discrétion, de changer ou de modifier des parties de ces Conditions à tout moment. Si nous le faisons, nous publierons les modifications sur [Connecteur pour l’accessibilité](:home) et indiquerons en haut de la page des Conditions la date à laquelle ces Conditions ont été révisées pour la dernière fois. Nous nous efforcerons également de vous notifier, soit par l’interface utilisateur de la Plateforme, soit dans une notification par courrier électronique, soit par d’autres moyens raisonnables. Ces modifications entreront en vigueur au plus tôt quatorze (14) jours après leur publication, à l’exception des modifications portant sur de nouvelles fonctions de la Plateforme ou des modifications apportées pour des raisons juridiques, qui entreront en vigueur immédiatement. En continuant à utiliser la Plateforme après la date d’entrée en vigueur de ces modifications, vous acceptez les nouvelles Conditions.

## QUESTIONS

Si vous avez des questions, vous savez que vous pouvez contacter l’IRIS par courrier électronique à l’adresse [<:email>].
                ',
            ]
        );
    }
}
