version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "production"
    assignees:
      - "greatislander"
    reviewers:
      - "greatislander"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "production"
    assignees:
      - "greatislander"
    reviewers:
      - "greatislander"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
      include: "scope"
