files:
  - source: /lang/en/*.php
    translation: /lang/%two_letters_code%/%original_file_name%
  - source: /lang/en.json
    translation: /%two_letters_code%.json
pull_request_title: 'chore(l10n): update translations'
pull_request_labels:
  - localization
commit_message: 'chore(l10n): translate %original_file_name% into %language%'
append_commit_message: false
