version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.cloud
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
      - mailhog

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_DIR}:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

  redis:
    image: redis:alpine
    volumes:
      - ${REDIS_DIR}:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  mailhog:
    image: mailhog/mailhog:latest
