version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.cloud
    environment:
      SNAPSHOTS_DISK: snapshots-s3
      SNAPSHOTS_AWS_SECRET_ACCESS_KEY: ${SNAPSHOTS_AWS_SECRET_ACCESS_KEY}
      SNAPSHOTS_AWS_DEFAULT_REGION: ${SNAPSHOTS_AWS_DEFAULT_REGION}
      SNAPSHOTS_AWS_BUCKET: ${SNAPSHOTS_AWS_BUCKET}
      SNAPSHOTS_AWS_URL: ${SNAPSHOTS_AWS_URL}
      SNAPSHOTS_AWS_ENDPOINT: ${SNAPSHOTS_AWS_ENDPOINT}
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html
      - ${APP_STORAGE_DIR}:/var/www/html/storage
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_DIR}:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

  redis:
    image: redis:alpine
    volumes:
      - ${REDIS_DIR}:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
