name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      value: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    attributes:
      label: Details
      value: |
        - Device:
        - Operating system:
        - Browser:
        - Link to affected page:
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
