name: Build JS and Sass assets

on:
  pull_request:
    branches: [ dev, prototype ]
    paths:
    - 'package.json'
    - 'package-lock.json'

jobs:
  asset-lint:

    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm install
      env:
        CI: true
    - name: Build assets
      run: npm run prod
