name: Build JS and Sass assets

on:
  push:
    branches: [ dev, prototype ]
    paths:
    - 'package.json'
    - 'package-lock.json'

jobs:
  build-assets:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm install
      env:
        CI: true
    - name: Build assets
      run: npm run prod
    - name: Commit built assets
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: build assets"
