name: Deploy dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy:
    if: github.repository == 'accessibility-exchange/platform'

    runs-on: ubuntu-latest

    concurrency: deploy-dev

    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v0.6.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: dev
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Deploy assets
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.SSH_PROXY_HOSTNAME }}
          proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
          proxy_key: ${{ secrets.SSH_PROXY_PRIVATE_KEY }}
          proxy_port: ${{ secrets.SSH_PROXY_PORT }}
          source: "public/build"
          target: "/srv/tae-dev/public/build"

      - name: Deploy stack
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.SSH_PROXY_HOSTNAME }}
          proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
          proxy_key: ${{ secrets.SSH_PROXY_PRIVATE_KEY }}
          proxy_port: ${{ secrets.SSH_PROXY_PORT }}
          script: |
            cd /srv/tae-dev && \
            cat public/build/manifest.json && \
            git checkout dev && \
            git pull && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml up -d --force-recreate && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml exec -T app composer install --optimize-autoloader && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml exec -T app ./artisan migrate:fresh --force && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml exec -T app ./artisan db:seed DevSeeder --force && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml exec -T app ./artisan view:clear && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml exec -T app ./artisan storage:link && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml exec -T app ./artisan google-fonts:fetch && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml exec -T app ./artisan icons:clear && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml exec -T app ./artisan icons:cache && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml exec -T app ./artisan route:cache && \
            /usr/local/bin/docker-compose -f docker-compose.cloud.yml exec -T app ./artisan config:cache

      - name: Wait
        run: sleep 15

      - name: Smoke test
        run: curl --location --no-buffer --retry 120 --retry-delay 1 https://tae-dev.inclusivedesign.ca

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.6.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://tae-dev.inclusivedesign.ca
