name: Deploy dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy:
    if: github.repository == 'accessibility-exchange/platform'

    runs-on: ubuntu-latest

    concurrency: deploy-dev

    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v1.3.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: dev
      - name: Deploy stack
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.SSH_PROXY_HOSTNAME }}
          proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
          proxy_key: ${{ secrets.SSH_PROXY_PRIVATE_KEY }}
          proxy_port: ${{ secrets.SSH_PROXY_PORT }}
          script: |
            cd /srv/tae-dev && \
            git checkout -f && \
            git checkout dev && \
            git pull && \
            ./bin/deploy-dev.sh

      - name: Wait
        run: sleep 15

      - name: Smoke test
        run: curl --location --no-buffer --retry 120 --retry-delay 1 https://tae-dev.inclusivedesign.ca

      - name: Update deployment status
        uses: bobheadxi/deployments@v1.3.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://tae-dev.inclusivedesign.ca
