name: Run Lighthouse CI

on:
  push:
    branches: [dev, staging, production]
  pull_request:
    branches: [dev, staging, production]

jobs:
  check-diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.git-diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v4
      - uses: greguintow/get-diff-action@v7
        id: git-diff
        with:
          PATTERNS: |
            composer.json
            composer.lock
            **/*.php
            package.json
            package-lock.json
            **/*.css
            **/*.js"

  lighthouse-ci:
    runs-on: ubuntu-latest
    needs: check-diff
    if: ${{ needs.check-diff.outputs.diff != '[]' && needs.check-diff.outputs.diff != '' }}
    strategy:
      matrix:
        php: [8.4]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # https://github.com/GoogleChrome/lighthouse-ci/issues/172
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Dependencies
        run: composer install -q --no-dev --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - name: Install dependencies
        run: npm install
        env:
          CI: true
      - name: Create test database
        run: |
          sudo systemctl start mysql.service
          mysqladmin create accessibilityexchange --user="root" --password="root"
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate keys
        run: |
          echo "CIPHERSWEET_KEY=\"$(openssl rand -hex 32)\"" >> .env
          php artisan key:generate
      - name: Run Laravel Server
        run: |
          php artisan migrate
          php artisan storage:link
          php artisan serve &
        env:
          DB_PASSWORD: root
          DB_HOST: localhost
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.9.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
