name: Publish release

on:
  push:
    branches: [dev]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: php
          package-name: accessibility-exchange/platform
          pull-request-title-pattern: "chore(release): release${component} ${version}"
