name: Release Please

on:
  push:
    branches:
      - dev

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          package-name: accessibility-exchange/platform
