name: Sync release to staging

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
  release:
    types: [published]

jobs:
  sync-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Open pull request to staging
        uses: tretuna/sync-branches@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: ${{ inputs.version || github.event.release.tag_name }}
          TO_BRANCH: "staging"
          PULL_REQUEST_TITLE: "chore(release): sync ${{ inputs.version || github.event.release.tag_name }} to staging"
